pysome/Exceptions.py,sha256=B5-wF0crO1LL5D1Mkm_43EvdpfkO-TP82lQW3qImM2E,285
pysome/Some.py,sha256=gsfjc9ycZAfLGVgLKb9TKUqKiM2TLZr8OtJ1uk1VL1w,7416
pysome/VSet.py,sha256=oebrGNQxusgmhxAnDTW5CLMClDWBEs4F4qLHfb9txVE,376
pysome/__init__.py,sha256=rMKDsgtwrhChzMW2wQWiOxOxVfx1X_dOTjcI2X9pLH4,112
pysome/expect.py,sha256=KyrJlKY_C7VkImGnnipvWTWnhWILhE4IoWvb5W6zqlw,341
pysome-0.0.1.dist-info/LICENSE,sha256=7EI8xVBu6h_7_JlVw-yPhhOZlpY9hP8wal7kHtqKT_E,1074
pysome-0.0.1.dist-info/METADATA,sha256=Adihdh2W95nCsS1qaG_MVyMRXrBeXYIiB8aCwZg0XgU,1270
pysome-0.0.1.dist-info/WHEEL,sha256=OqRkF0eY5GHssMorFjlbTIq072vpHpF60fIQA6lS9xA,92
pysome-0.0.1.dist-info/top_level.txt,sha256=qRDMLX1zF9agJO2cswilPCO8ry6vrMXeRgpPpJoqxcM,7
pysome-0.0.1.dist-info/RECORD,,
